package cat.itacademy.barcelonactiva.rucker.dario.s05.t01.n03_WebClient.flowerdto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Builder
public class Flowerdto {

    @Schema(description = "This is the id of the flower. The id is autogenerated by the database")
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    Integer id;
    @Schema(description = "This field is the NAME of the flower", example = "rose", required = true)
    String name;
    @Schema(description = "This field is the NAME of the COUNTRY and must be written in english", example = "Spain", required = true)
    String country;
    @Schema(description = "This field will be returned by the method entityToDto. It is used to indicate if the country belongs to the EU", example = "EU")
    private String flowerType;

    @Schema(description = "This array contains the list of the countrys of the EU and it is provided by the administrator")
    private final List<String> countrys = Arrays.asList("Austria", "Belgium", "Bulgaria",
            "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland",
            "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia",
            "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal",
            "Romania", "Slovakia", "Slovenia", "Spain", "Sweden");


}
